[0m03:21:44.935155 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000200F47CC400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000200F73E5C10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000200F73E5F70>]}


============================== 03:21:44.940161 | decf2603-2e2d-42c5-9e64-f41f79bf91eb ==============================
[0m03:21:44.940161 [info ] [MainThread]: Running with dbt=1.8.8
[0m03:21:44.941189 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\katep\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt init', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m03:22:08.615076 [debug] [MainThread]: Starter project path: C:\Users\katep\miniconda3\envs\personalproject\lib\site-packages\dbt\include\starter_project
[0m03:22:08.657870 [info ] [MainThread]: 
Your new dbt project "taxi_rides" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m03:22:08.658868 [info ] [MainThread]: Setting up your profile.
[0m03:26:16.744166 [info ] [MainThread]: Profile taxi_rides written to C:\Users\katep\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m03:26:16.747095 [debug] [MainThread]: Command `dbt init` succeeded at 03:26:16.747095 after 271.91 seconds
[0m03:26:16.748153 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000200F47CC400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000200F737BFA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000200F737BA30>]}
[0m03:26:16.749094 [debug] [MainThread]: Flushing usage events
[0m03:26:27.605126 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001900089EFA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000190034C9FD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000190034C9DC0>]}


============================== 03:26:27.609257 | 85f22249-aa0b-4ec7-ba3c-109941701666 ==============================
[0m03:26:27.609257 [info ] [MainThread]: Running with dbt=1.8.8
[0m03:26:27.610257 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\katep\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m03:26:27.629781 [info ] [MainThread]: dbt version: 1.8.8
[0m03:26:27.630785 [info ] [MainThread]: python version: 3.9.21
[0m03:26:27.631782 [info ] [MainThread]: python path: C:\Users\katep\miniconda3\envs\personalproject\python.exe
[0m03:26:27.631782 [info ] [MainThread]: os info: Windows-10-10.0.22631-SP0
[0m03:26:30.292470 [debug] [MainThread]: Redshift adapter: Setting redshift_connector to ERROR
[0m03:26:30.293470 [debug] [MainThread]: Redshift adapter: Setting redshift_connector.core to ERROR
[0m03:26:30.362044 [info ] [MainThread]: Using profiles dir at C:\Users\katep\.dbt
[0m03:26:30.362998 [info ] [MainThread]: Using profiles.yml file at C:\Users\katep\.dbt\profiles.yml
[0m03:26:30.363999 [info ] [MainThread]: Using dbt_project.yml file at D:\OneDrive\Desktop\zoomcamp\zoomcamp_2025\week_4\dbt_project.yml
[0m03:26:30.365002 [info ] [MainThread]: Configuration:
[0m03:26:30.366003 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m03:26:30.367001 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m03:26:30.367001 [info ] [MainThread]: Required dependencies:
[0m03:26:30.368000 [debug] [MainThread]: Executing "git --help"
[0m03:26:30.426134 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--config-env=<name>=<envvar>] <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m03:26:30.426134 [debug] [MainThread]: STDERR: "b''"
[0m03:26:30.427153 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m03:26:30.427153 [info ] [MainThread]: Connection test skipped since no profile was found
[0m03:26:30.428658 [info ] [MainThread]: [31m2 checks failed:[0m
[0m03:26:30.428658 [info ] [MainThread]: Could not load dbt_project.yml
Profile loading failed for the following reason:
Runtime Error
  The profile 'test' does not have a target named 'dev'. The valid target names for this profile are:
   - prod


[0m03:26:30.429669 [info ] [MainThread]: Project loading failed for the following reason:
 project path <D:\OneDrive\Desktop\zoomcamp\zoomcamp_2025\week_4\dbt_project.yml> not found

[0m03:26:30.430663 [debug] [MainThread]: Command `dbt debug` failed at 03:26:30.430663 after 2.91 seconds
[0m03:26:30.431682 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001900089EFA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019017AA0FD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000190034C9C70>]}
[0m03:26:30.431682 [debug] [MainThread]: Flushing usage events
[0m03:27:14.432839 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D4842EFA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D4B058BB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D4B058F70>]}


============================== 03:27:14.445895 | be47fd00-505e-4d26-b619-e20e9a2b4f14 ==============================
[0m03:27:14.445895 [info ] [MainThread]: Running with dbt=1.8.8
[0m03:27:14.448904 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\katep\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m03:27:14.496101 [info ] [MainThread]: dbt version: 1.8.8
[0m03:27:14.501104 [info ] [MainThread]: python version: 3.9.21
[0m03:27:14.507340 [info ] [MainThread]: python path: C:\Users\katep\miniconda3\envs\personalproject\python.exe
[0m03:27:14.515338 [info ] [MainThread]: os info: Windows-10-10.0.22631-SP0
[0m03:27:19.809275 [debug] [MainThread]: Redshift adapter: Setting redshift_connector to ERROR
[0m03:27:19.810293 [debug] [MainThread]: Redshift adapter: Setting redshift_connector.core to ERROR
[0m03:27:19.913574 [info ] [MainThread]: Using profiles dir at C:\Users\katep\.dbt
[0m03:27:19.914584 [info ] [MainThread]: Using profiles.yml file at C:\Users\katep\.dbt\profiles.yml
[0m03:27:19.916522 [info ] [MainThread]: Using dbt_project.yml file at D:\OneDrive\Desktop\zoomcamp\zoomcamp_2025\week_4\dbt_project.yml
[0m03:27:19.917492 [info ] [MainThread]: Configuration:
[0m03:27:19.918545 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m03:27:19.920577 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m03:27:19.921572 [info ] [MainThread]: Required dependencies:
[0m03:27:19.922497 [debug] [MainThread]: Executing "git --help"
[0m03:27:19.955757 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--config-env=<name>=<envvar>] <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m03:27:19.957844 [debug] [MainThread]: STDERR: "b''"
[0m03:27:19.958839 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m03:27:19.959756 [info ] [MainThread]: Connection test skipped since no profile was found
[0m03:27:19.960838 [info ] [MainThread]: [31m2 checks failed:[0m
[0m03:27:19.961762 [info ] [MainThread]: Could not load dbt_project.yml
Profile loading failed for the following reason:
Runtime Error
  The profile 'taxi_rides' does not have a target named 'prod'. The valid target names for this profile are:
   - dev

Runtime Error
  The profile 'test' does not have a target named 'dev'. The valid target names for this profile are:
   - prod


[0m03:27:19.962842 [info ] [MainThread]: Project loading failed for the following reason:
 project path <D:\OneDrive\Desktop\zoomcamp\zoomcamp_2025\week_4\dbt_project.yml> not found

[0m03:27:19.963763 [debug] [MainThread]: Command `dbt debug` failed at 03:27:19.963763 after 5.76 seconds
[0m03:27:19.964781 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D4842EFA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D5F725220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026D5F728700>]}
[0m03:27:19.965781 [debug] [MainThread]: Flushing usage events
[0m03:27:39.895970 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002329C57EFA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002329F1A9FD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002329F1A9DC0>]}


============================== 03:27:39.900477 | 9b85893d-8d6e-4c6c-9221-d40f200a4a3f ==============================
[0m03:27:39.900477 [info ] [MainThread]: Running with dbt=1.8.8
[0m03:27:39.901479 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\katep\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt debug', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m03:27:39.916478 [info ] [MainThread]: dbt version: 1.8.8
[0m03:27:39.917478 [info ] [MainThread]: python version: 3.9.21
[0m03:27:39.918478 [info ] [MainThread]: python path: C:\Users\katep\miniconda3\envs\personalproject\python.exe
[0m03:27:39.918478 [info ] [MainThread]: os info: Windows-10-10.0.22631-SP0
[0m03:27:41.968365 [debug] [MainThread]: Redshift adapter: Setting redshift_connector to ERROR
[0m03:27:41.969414 [debug] [MainThread]: Redshift adapter: Setting redshift_connector.core to ERROR
[0m03:27:42.020971 [info ] [MainThread]: Using profiles dir at C:\Users\katep\.dbt
[0m03:27:42.021973 [info ] [MainThread]: Using profiles.yml file at C:\Users\katep\.dbt\profiles.yml
[0m03:27:42.022973 [info ] [MainThread]: Using dbt_project.yml file at D:\OneDrive\Desktop\zoomcamp\zoomcamp_2025\week_4\dbt_project.yml
[0m03:27:42.023973 [info ] [MainThread]: Configuration:
[0m03:27:42.025001 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m03:27:42.025976 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m03:27:42.026989 [info ] [MainThread]: Required dependencies:
[0m03:27:42.027987 [debug] [MainThread]: Executing "git --help"
[0m03:27:42.054971 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--config-env=<name>=<envvar>] <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m03:27:42.055978 [debug] [MainThread]: STDERR: "b''"
[0m03:27:42.056972 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m03:27:42.057971 [info ] [MainThread]: Connection test skipped since no profile was found
[0m03:27:42.058989 [info ] [MainThread]: [31m2 checks failed:[0m
[0m03:27:42.059973 [info ] [MainThread]: Could not load dbt_project.yml
Profile loading failed for the following reason:
Runtime Error
  The profile 'taxi_rides' does not have a target named 'prod'. The valid target names for this profile are:
   - dev


[0m03:27:42.060971 [info ] [MainThread]: Project loading failed for the following reason:
 project path <D:\OneDrive\Desktop\zoomcamp\zoomcamp_2025\week_4\dbt_project.yml> not found

[0m03:27:42.062972 [debug] [MainThread]: Command `dbt debug` failed at 03:27:42.062972 after 2.25 seconds
[0m03:27:42.062972 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002329C57EFA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000232B3780FD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002329F239970>]}
[0m03:27:42.063972 [debug] [MainThread]: Flushing usage events
[0m03:27:57.620373 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002698CF6EFA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002698FBA7FD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002698FBA7DC0>]}


============================== 03:27:57.624375 | 04678460-eb6e-4572-9ee9-978bf949b6ac ==============================
[0m03:27:57.624375 [info ] [MainThread]: Running with dbt=1.8.8
[0m03:27:57.625390 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\katep\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt init', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m03:28:40.769323 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002730922DFA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002730BE58460>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002730BE580A0>]}


============================== 03:28:40.773331 | c6768d4a-8b21-4c15-990e-b018ce7b0e79 ==============================
[0m03:28:40.773331 [info ] [MainThread]: Running with dbt=1.8.8
[0m03:28:40.774331 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\katep\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m03:28:40.789332 [info ] [MainThread]: dbt version: 1.8.8
[0m03:28:40.789332 [info ] [MainThread]: python version: 3.9.21
[0m03:28:40.790357 [info ] [MainThread]: python path: C:\Users\katep\miniconda3\envs\personalproject\python.exe
[0m03:28:40.791347 [info ] [MainThread]: os info: Windows-10-10.0.22631-SP0
[0m03:28:42.850434 [debug] [MainThread]: Redshift adapter: Setting redshift_connector to ERROR
[0m03:28:42.851520 [debug] [MainThread]: Redshift adapter: Setting redshift_connector.core to ERROR
[0m03:28:42.908472 [info ] [MainThread]: Using profiles dir at C:\Users\katep\.dbt
[0m03:28:42.909474 [info ] [MainThread]: Using profiles.yml file at C:\Users\katep\.dbt\profiles.yml
[0m03:28:42.910472 [info ] [MainThread]: Using dbt_project.yml file at D:\OneDrive\Desktop\zoomcamp\zoomcamp_2025\week_4\dbt_project.yml
[0m03:28:42.911476 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m03:28:42.912473 [debug] [MainThread]: Command `dbt debug` failed at 03:28:42.912473 after 2.22 seconds
[0m03:28:42.913484 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002730922DFA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002731CF3DD00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002730BE3D580>]}
[0m03:28:42.913484 [debug] [MainThread]: Flushing usage events
